version: '3.4'

services:
  webcore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44331
    ports:
      - "51347:80"
      - "44331:443"
    links:
      - Sql1
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  Sql1:
    image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    environment:
      - SA_PASSWORD=ABCabc123
      - ACCEPT_EULA=Y
    ports:
      - "1435:1433"
    volumes:
      - d:/DockerDB/data:/var/opt/mssql